/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import control.CekTensiControl;
import control.DokterControl;
import control.PembeliControl;
import exception.InputIdException;
import exception.InputKosongException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.util.List;
import model.Cek_tensi;
import model.Dokter;
import model.Pembeli;
import table.TableCekTensi;
/**
 *
 * @author ASUS
 */
public class CekTensiView extends javax.swing.JFrame {

    /**
     * Creates new form CekTensiView
     */
    private CekTensiControl cekTensiControl;
    private DokterControl dokterControl;
    private PembeliControl pembeliControl;
    String action = null;
    List<Dokter> listDokter;
    List<Pembeli> listPasien;
    int selectedId=0;
            
            
            
    public CekTensiView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        dokterControl = new DokterControl();
        pembeliControl = new PembeliControl();
        cekTensiControl = new CekTensiControl();
        showCekTensi();
        setDokterToDropdown();
        setPasientToDropdown();
        setRadioTensi(false);
        GrubHasil.clearSelection();
    }
    
    public void setComponent(boolean value){
        txtId.setEnabled(value);
        txtNoAntri.setEnabled(value);
        DokterDropDown.setEnabled(value);
        PasienDropDown.setEnabled(value);
        
        btnSave.setEnabled(value);
        btnCancel.setEnabled(value);
        
    }
    
    public void setEditDeleteBtn(boolean value){
        btnUbah.setEnabled(value);
        btnHapus.setEnabled(value);
    }
    
    public void clearText(){
        cariInput.setText("");
        txtId.setText("");
        txtNoAntri.setText("");
        GrubHasil.clearSelection();
        DokterDropDown.setSelectedItem(ABORT);
        PasienDropDown.setSelectedItem(ABORT);
    }
    public void setRadioTensi(Boolean value){
        RadioTinggi.setEnabled(value);
        RadioRendah.setEnabled(value);
        RadioNormal.setEnabled(value);
    }
    public void setDokterToDropdown(){
        listDokter = dokterControl.showListDokter();
        for (int i = 0; i < listDokter.size(); i++) {
            DokterDropDown.addItem(listDokter.get(i));
        }
    }
    public void setPasientToDropdown(){
        listPasien = pembeliControl.showListPembeli();
        for (int i = 0; i < listPasien.size(); i++) {
            PasienDropDown.addItem(listPasien.get(i));
        }
    }
    
    public void showCekTensi(){
        tableCekTensi.setModel(cekTensiControl.showDataCektensi(""));
    }
    
    public void InputIdException() throws InputIdException{
        if(txtId.getText().length()<5 || txtId.getText().length()>5){
            throw new InputIdException();
        }
    }
    
    public void inputKosongException() throws InputKosongException{
        
        if(txtId.getText().isEmpty() || Integer.parseInt(txtNoAntri.getText())<1 ||
                DokterDropDown.getSelectedIndex()==-1 || PasienDropDown.getSelectedIndex()==-1){
            throw new InputKosongException();
        }
            
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrubHasil = new javax.swing.ButtonGroup();
        sidebarPanel = new javax.swing.JPanel();
        LogoPanel = new javax.swing.JPanel();
        iconApotek = new javax.swing.JLabel();
        lblNamaApotek = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        iconCekTensi = new javax.swing.JLabel();
        lblCekTensi = new javax.swing.JLabel();
        PembelianPanel = new javax.swing.JPanel();
        iconPembelian = new javax.swing.JLabel();
        lblPembelian = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        titlePanel2 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        cariInput = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        isiPanel = new javax.swing.JPanel();
        PasienDropDown = new javax.swing.JComboBox<>();
        DokterDropDown = new javax.swing.JComboBox<>();
        lblPembeli = new javax.swing.JLabel();
        lblObat = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblTangga = new javax.swing.JLabel();
        txtNoAntri = new javax.swing.JTextField();
        lblJumlah = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCekTensi = new javax.swing.JTable();
        RadioTinggi = new javax.swing.JRadioButton();
        RadioNormal = new javax.swing.JRadioButton();
        RadioRendah = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(17, 192, 41));

        LogoPanel.setBackground(new java.awt.Color(17, 192, 41));
        LogoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoPanelMouseClicked(evt);
            }
        });

        iconApotek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconApotek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo2.png"))); // NOI18N

        lblNamaApotek.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18)); // NOI18N
        lblNamaApotek.setText("Aptotek Doni Wijaya");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addGroup(LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNamaApotek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LogoPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(iconApotek, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconApotek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamaApotek)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(61, 223, 36));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        iconCekTensi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCekTensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logotensi2.png"))); // NOI18N

        lblCekTensi.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblCekTensi.setText("Cek Tensi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconCekTensi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCekTensi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(iconCekTensi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblCekTensi)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PembelianPanel.setBackground(new java.awt.Color(17, 192, 41));
        PembelianPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PembelianPanelMouseClicked(evt);
            }
        });

        iconPembelian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo Pembelian.png"))); // NOI18N

        lblPembelian.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblPembelian.setText("Pembelian");

        javax.swing.GroupLayout PembelianPanelLayout = new javax.swing.GroupLayout(PembelianPanel);
        PembelianPanel.setLayout(PembelianPanelLayout);
        PembelianPanelLayout.setHorizontalGroup(
            PembelianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PembelianPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPembelian)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PembelianPanelLayout.setVerticalGroup(
            PembelianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PembelianPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconPembelian)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PembelianPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPembelian)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PembelianPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PembelianPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        containerPanel.setBackground(new java.awt.Color(72, 221, 125));

        titlePanel2.setBackground(new java.awt.Color(220, 213, 213));
        titlePanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cek Tensi"));

        btnTambah.setBackground(new java.awt.Color(10, 236, 41));
        btnTambah.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(10, 236, 41));
        btnUbah.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(10, 236, 41));
        btnHapus.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        judul.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        judul.setText("CEK TENSI");

        javax.swing.GroupLayout titlePanel2Layout = new javax.swing.GroupLayout(titlePanel2);
        titlePanel2.setLayout(titlePanel2Layout);
        titlePanel2Layout.setHorizontalGroup(
            titlePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanel2Layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cariInput, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addGap(25, 25, 25))
                    .addGroup(titlePanel2Layout.createSequentialGroup()
                        .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        titlePanel2Layout.setVerticalGroup(
            titlePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(judul)
                .addGap(18, 18, 18)
                .addGroup(titlePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(cariInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        isiPanel.setBackground(new java.awt.Color(220, 213, 213));
        isiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));

        PasienDropDown.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        PasienDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasienDropDownActionPerformed(evt);
            }
        });

        DokterDropDown.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        lblPembeli.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblPembeli.setText("Pasien");

        lblObat.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblObat.setText("Dokter");

        lblId.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblId.setText("id Cek Tensi");

        txtId.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        lblTangga.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblTangga.setText("Nomor Antrian");

        txtNoAntri.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        lblJumlah.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblJumlah.setText("Hasil");

        btnSave.setBackground(new java.awt.Color(10, 236, 41));
        btnSave.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(10, 236, 41));
        btnCancel.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tableCekTensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCekTensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCekTensiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCekTensi);

        GrubHasil.add(RadioTinggi);
        RadioTinggi.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        RadioTinggi.setText("Darah Tinggi");
        RadioTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTinggiActionPerformed(evt);
            }
        });

        GrubHasil.add(RadioNormal);
        RadioNormal.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        RadioNormal.setText("Darah Normal");
        RadioNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNormalActionPerformed(evt);
            }
        });

        GrubHasil.add(RadioRendah);
        RadioRendah.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        RadioRendah.setText("Darah Rendah");
        RadioRendah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioRendahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout isiPanelLayout = new javax.swing.GroupLayout(isiPanel);
        isiPanel.setLayout(isiPanelLayout);
        isiPanelLayout.setHorizontalGroup(
            isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiPanelLayout.createSequentialGroup()
                        .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(isiPanelLayout.createSequentialGroup()
                                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoAntri, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTangga, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasienDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPembeli)))
                            .addGroup(isiPanelLayout.createSequentialGroup()
                                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiPanelLayout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancel))
                                    .addComponent(DokterDropDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblObat))))
                        .addGap(38, 38, 38))
                    .addGroup(isiPanelLayout.createSequentialGroup()
                        .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioRendah)
                            .addComponent(lblJumlah)
                            .addComponent(RadioTinggi)
                            .addComponent(RadioNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        isiPanelLayout.setVerticalGroup(
            isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObat)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DokterDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTangga)
                    .addComponent(lblPembeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoAntri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasienDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblJumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioTinggi)
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnCancel)))
                    .addGroup(isiPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadioNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadioRendah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(isiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        clearText();
        setRadioTensi(true);
        action ="Tambah";
        DokterDropDown.setSelectedIndex(0);
        PasienDropDown.setSelectedIndex(0);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        txtId.setEnabled(false);
        setRadioTensi(true);

        action = "Ubah";
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:

            try{
                cekTensiControl.deleteDataCekTensi(txtId.getText());
                clearText();
                showCekTensi();
                setComponent(false);
                setEditDeleteBtn(false);
            }catch(Exception e){
                System.out.println("Error : " + e.getMessage());
            }
            break;

            case 1:
            break;
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);

        try{
            TableCekTensi cek_tensi = cekTensiControl.showDataCektensi(cariInput.getText());
            if(cek_tensi.getRowCount()==0){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null,"Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                tableCekTensi.setModel(cek_tensi);
            }
            clearText();
        }catch(Exception e){
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        try{
        inputKosongException();
        InputIdException();
        
        int selectedIndex = DokterDropDown.getSelectedIndex();
        Dokter selectedObat = listDokter.get(selectedIndex);
        
        selectedIndex = PasienDropDown.getSelectedIndex();
        Pembeli selectedPembeli = listPasien.get(selectedIndex);
        
        String hasil = "";
//        if(RadioNormal.isSelected()){
//           hasil = "Pasien "+listPasien.get(selectedIndex)+" Sehat";
//        }else if(RadioRendah.isSelected()){
//            hasil = "Pasien "+listPasien.get(selectedIndex)+" Memiliki Darah Rendah";
//        }else{
//            hasil = "Pasien "+listPasien.get(selectedIndex)+" Memiliki Darah Tinggi";
//        }

            if(RadioNormal.isSelected()){
                hasil = "Pasien "+listPasien.get(selectedIndex)+" Sehat";
             }else if(RadioRendah.isSelected()){
                 hasil = "Pasien "+listPasien.get(selectedIndex)+" Memiliki Darah Rendah";
             }else{
                 hasil = "Pasien "+listPasien.get(selectedIndex)+" Memiliki Darah Tinggi";
             }
        

        if(action.equals("Tambah")){
            Cek_tensi ct = new Cek_tensi(txtId.getText(),
                Integer.parseInt(txtNoAntri.getText()), hasil, selectedObat, selectedPembeli);
            cekTensiControl.insertDataCekTensi(ct);
        }else{
            Cek_tensi ct = new Cek_tensi(txtId.getText(),
                Integer.parseInt(txtNoAntri.getText()), hasil, selectedObat, selectedPembeli);
            cekTensiControl.updateDataCekTensi(ct);
        }
        clearText();
        showCekTensi();
        setComponent(false);
        setRadioTensi(false);
        GrubHasil.clearSelection();
        
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(InputIdException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Hanya dapat menginputkan angka");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioTensi(false);
        GrubHasil.clearSelection();
        clearText();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tableCekTensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCekTensiMouseClicked
        // TODO add your handling code here:
        int selectedIndex = PasienDropDown.getSelectedIndex();
        Pembeli selectedPembeli = listPasien.get(selectedIndex);
        setComponent(false);

        int indexPembeli=-1;
        int indexDokter=-1;
        
        int clickedRow = tableCekTensi.getSelectedRow();
        TableModel tableModel = tableCekTensi.getModel();

        txtId.setText(tableModel.getValueAt(clickedRow, 4).toString());
        txtNoAntri.setText(tableModel.getValueAt(clickedRow, 0).toString());

        String id_Dokter = tableModel.getValueAt(clickedRow, 5).toString();
        for (Dokter dokter : listDokter) {
            if(dokter.getId().equals(id_Dokter)){
                indexDokter = listDokter.indexOf(dokter);
            }
        }
        DokterDropDown.setSelectedIndex(indexDokter);

        String id_Pembeli = tableModel.getValueAt(clickedRow, 6).toString();
        for (Pembeli pembeli : listPasien) {
            if(pembeli.getId().equals(id_Pembeli)){
                indexPembeli = listPasien.indexOf(pembeli);
            }
        }
        PasienDropDown.setSelectedIndex(indexPembeli);
        
        String hasil = tableModel.getValueAt(clickedRow, 3).toString();
        if(hasil.contains("Tinggi")) {
            RadioTinggi.setSelected(true);
        }else if(hasil.contains("Sehat")) {
            RadioNormal.setSelected(true);
        }else if(hasil.contains("Rendah")) {
            RadioRendah.setSelected(true);
        }
        setEditDeleteBtn(true);
        setRadioTensi(false);
    }//GEN-LAST:event_tableCekTensiMouseClicked

    private void RadioTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioTinggiActionPerformed

    private void PasienDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasienDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasienDropDownActionPerformed

    private void RadioRendahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioRendahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioRendahActionPerformed

    private void PembelianPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PembelianPanelMouseClicked
        // TODO add your handling code here:
        PembelianView pv = new PembelianView();
        this.dispose();
        pv.setVisible(true);
    }//GEN-LAST:event_PembelianPanelMouseClicked

    private void LogoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoPanelMouseClicked
        // TODO add your handling code here:
        LobbyView lv = new LobbyView();
        this.dispose();
        lv.setVisible(true);
    }//GEN-LAST:event_LogoPanelMouseClicked

    private void RadioNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioNormalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekTensiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekTensiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekTensiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekTensiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekTensiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Dokter> DokterDropDown;
    private javax.swing.ButtonGroup GrubHasil;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JComboBox<Pembeli> PasienDropDown;
    private javax.swing.JPanel PembelianPanel;
    private javax.swing.JRadioButton RadioNormal;
    private javax.swing.JRadioButton RadioRendah;
    private javax.swing.JRadioButton RadioTinggi;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField cariInput;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel iconApotek;
    private javax.swing.JLabel iconCekTensi;
    private javax.swing.JLabel iconPembelian;
    private javax.swing.JPanel isiPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel lblCekTensi;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblNamaApotek;
    private javax.swing.JLabel lblObat;
    private javax.swing.JLabel lblPembeli;
    private javax.swing.JLabel lblPembelian;
    private javax.swing.JLabel lblTangga;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTable tableCekTensi;
    private javax.swing.JPanel titlePanel2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNoAntri;
    // End of variables declaration//GEN-END:variables
}
