/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
import control.ObatControl;
import control.PembeliControl;
import control.PembelianControl;
import exception.InputIdException;
import exception.InputKosongException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.util.List;
import model.Obat;
import model.Pembeli;
import model.Pembelian;
import table.TablePembelian;
public class PembelianView extends javax.swing.JFrame {

    /**
     * Creates new form PembelianView
     */
    private ObatControl obatControl;
    private PembeliControl pembeliControl;
    private PembelianControl pembelianControl;
    String action=null;
    List<Obat> listObat;
    List<Pembeli> listPembeli;
    int selectedId=0;
    
    
    public PembelianView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        obatControl = new ObatControl();
        pembeliControl = new PembeliControl();
        pembelianControl = new PembelianControl();
        showPembelian();
        setObatToDropdown();
        setPembelitToDropdown();
        
    }
    
    public void setComponent(boolean value){
        txtId.setEnabled(value);
        txtJumlah.setEnabled(value);
        txtTanggalPembelian.setEnabled(value);
        txtCatatan.setEnabled(value);
        ObatDropDown.setEnabled(value);
        PembeliDropDown.setEnabled(value);
        
        btnSave.setEnabled(value);
        btnCancel.setEnabled(value);
        
    }
    public void setEditDeleteBtn(boolean value){
        btnEdit.setEnabled(value);
        btnDelete.setEnabled(value);
    }
    
    public void clearText(){
        searchInput.setText("");
        txtId.setText("");
        txtJumlah.setText("");
        txtCatatan.setText("");
        txtTanggalPembelian.setText("");
        ObatDropDown.setSelectedItem(ABORT);
        PembeliDropDown.setSelectedItem(ABORT);
    }
    
    public void setObatToDropdown(){
        listObat = obatControl.showListObat();
        for (int i = 0; i < listObat.size(); i++) {
            ObatDropDown.addItem(listObat.get(i));
        }
    }
    public void setPembelitToDropdown(){
        listPembeli = pembeliControl.showListPembeli();
        for (int i = 0; i < listPembeli.size(); i++) {
            PembeliDropDown.addItem(listPembeli.get(i));
        }
    }
    
    public void showPembelian(){
        tablePembelian.setModel(pembelianControl.showDataPembelian(""));
    }
    
    public void inputKosongException() throws InputKosongException{
        
        if(txtId.getText().isEmpty() || txtTanggalPembelian.getText().isEmpty()|| Integer.parseInt(txtJumlah.getText())<1 ||
                ObatDropDown.getSelectedIndex()==-1 || PembeliDropDown.getSelectedIndex()==-1){
            throw new InputKosongException();
        }
            
    }
    public void InputIdException() throws InputIdException{
        if(txtId.getText().length()<5 || txtId.getText().length()>5){
            throw new InputIdException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePembelian1 = new javax.swing.JTable();
        sidebarPanel = new javax.swing.JPanel();
        LogoPanel = new javax.swing.JPanel();
        iconApotek = new javax.swing.JLabel();
        lblNamaApotek = new javax.swing.JLabel();
        CekTensiPanel = new javax.swing.JPanel();
        iconCekTensi = new javax.swing.JLabel();
        lblCekTensi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iconPembelian = new javax.swing.JLabel();
        lblPembelian = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        isiPanel = new javax.swing.JPanel();
        PembeliDropDown = new javax.swing.JComboBox<>();
        ObatDropDown = new javax.swing.JComboBox<>();
        lblPembeli = new javax.swing.JLabel();
        lblObat = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblTangga = new javax.swing.JLabel();
        txtTanggalPembelian = new javax.swing.JTextField();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        lblCatatan = new javax.swing.JLabel();
        txtCatatan = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePembelian = new javax.swing.JTable();

        tablePembelian1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(17, 192, 41));

        LogoPanel.setBackground(new java.awt.Color(17, 192, 41));
        LogoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoPanelMouseClicked(evt);
            }
        });

        iconApotek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconApotek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo2.png"))); // NOI18N

        lblNamaApotek.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18)); // NOI18N
        lblNamaApotek.setText("Aptotek Doni Wijaya");

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNamaApotek, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(iconApotek, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconApotek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamaApotek)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CekTensiPanel.setBackground(new java.awt.Color(17, 192, 41));
        CekTensiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CekTensiPanelMouseClicked(evt);
            }
        });

        iconCekTensi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCekTensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logotensi2.png"))); // NOI18N

        lblCekTensi.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblCekTensi.setText("Cek Tensi");

        javax.swing.GroupLayout CekTensiPanelLayout = new javax.swing.GroupLayout(CekTensiPanel);
        CekTensiPanel.setLayout(CekTensiPanelLayout);
        CekTensiPanelLayout.setHorizontalGroup(
            CekTensiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CekTensiPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconCekTensi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCekTensi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CekTensiPanelLayout.setVerticalGroup(
            CekTensiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CekTensiPanelLayout.createSequentialGroup()
                .addGroup(CekTensiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CekTensiPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(iconCekTensi))
                    .addGroup(CekTensiPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblCekTensi)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(61, 223, 36));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        iconPembelian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo Pembelian.png"))); // NOI18N

        lblPembelian.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblPembelian.setText("Pembelian");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPembelian)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconPembelian)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPembelian)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CekTensiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CekTensiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(72, 221, 125));

        titlePanel.setBackground(new java.awt.Color(220, 213, 213));
        titlePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu Pembelian"));

        btnAdd.setBackground(new java.awt.Color(10, 236, 41));
        btnAdd.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(10, 236, 41));
        btnEdit.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(10, 236, 41));
        btnDelete.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setText("PEMBELIAN");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(25, 25, 25))
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        isiPanel.setBackground(new java.awt.Color(220, 213, 213));
        isiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));

        PembeliDropDown.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        ObatDropDown.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        lblPembeli.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblPembeli.setText("Pembeli");

        lblObat.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblObat.setText("Obat");

        lblId.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblId.setText("id Pembelian");

        txtId.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        lblTangga.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblTangga.setText("Tanggal Pembelian");

        txtTanggalPembelian.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        lblJumlah.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblJumlah.setText("Jumlah");

        txtJumlah.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        lblCatatan.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblCatatan.setText("Catatan");

        txtCatatan.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        btnSave.setBackground(new java.awt.Color(10, 236, 41));
        btnSave.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(10, 236, 41));
        btnCancel.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tablePembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePembelian);

        javax.swing.GroupLayout isiPanelLayout = new javax.swing.GroupLayout(isiPanel);
        isiPanel.setLayout(isiPanelLayout);
        isiPanelLayout.setHorizontalGroup(
            isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiPanelLayout.createSequentialGroup()
                        .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblJumlah)
                            .addComponent(txtCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addGap(38, 38, 38))
                    .addGroup(isiPanelLayout.createSequentialGroup()
                        .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTanggalPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTangga, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblObat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ObatDropDown, 0, 290, Short.MAX_VALUE)
                            .addComponent(lblPembeli)
                            .addComponent(PembeliDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        isiPanelLayout.setVerticalGroup(
            isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObat)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObatDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblPembeli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PembeliDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(isiPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblTangga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTanggalPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblJumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(isiPanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(isiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSave)
                                    .addComponent(btnCancel)))
                            .addGroup(isiPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblCatatan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isiPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        clearText();
        
        action ="Tambah";
        ObatDropDown.setSelectedIndex(0);
        PembeliDropDown.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
        inputKosongException();
        InputIdException();
                
        int selectedIndex = ObatDropDown.getSelectedIndex();
        Obat selectedObat = listObat.get(selectedIndex);
        
        selectedIndex = PembeliDropDown.getSelectedIndex();
        Pembeli selectedPembeli = listPembeli.get(selectedIndex);

        int harga = listObat.get(selectedIndex).getHarga();
        int total_harga = harga * Integer.parseInt(txtJumlah.getText());

        if(action.equals("Tambah")){
            Pembelian p = new Pembelian(txtId.getText(),
                txtTanggalPembelian.getText(), txtCatatan.getText(), Integer.parseInt(txtJumlah.getText()),total_harga  , selectedObat, selectedPembeli);
            pembelianControl.insertDataPembelian(p);
        }else{
            Pembelian p = new Pembelian(txtId.getText(),
                txtTanggalPembelian.getText(), txtCatatan.getText(), Integer.parseInt(txtJumlah.getText()), total_harga , selectedObat, selectedPembeli);
            pembelianControl.updateDataPembelian(p);
        }
        clearText();
        showPembelian();
        setComponent(false);
        
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(InputIdException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Hanya dapat menginputkan angka");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        txtId.setEnabled(false);
        
        action = "Ubah";
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                
            try{
                pembelianControl.deleteDataPembelian(txtId.getText());
                clearText();
                showPembelian();
                setComponent(false);
                setEditDeleteBtn(false);
            }catch(Exception e){
                System.out.println("Error : " + e.getMessage());
            }
            break;
            
            case 1:
                break;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tablePembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePembelianMouseClicked
        // TODO add your handling code here:
        
        setComponent(false);
        
        int indexPembeli=-1;
        int indexObat=-1;
        
        int clickedRow = tablePembelian.getSelectedRow();
        TableModel tableModel = tablePembelian.getModel();
        
        txtId.setText(tableModel.getValueAt(clickedRow, 8).toString());
        txtTanggalPembelian.setText(tableModel.getValueAt(clickedRow, 3).toString());
        txtJumlah.setText(tableModel.getValueAt(clickedRow, 4).toString());
        txtCatatan.setText(tableModel.getValueAt(clickedRow, 7).toString());
        
        String id_Obat = tableModel.getValueAt(clickedRow, 9).toString();
        for (Obat obat : listObat) {
            if(obat.getId().equals(id_Obat)){
                indexObat = listObat.indexOf(obat);
            }
        }
        ObatDropDown.setSelectedIndex(indexObat);
        
        String id_Pembeli = tableModel.getValueAt(clickedRow, 10).toString();
        for (Pembeli pembeli : listPembeli) {
            if(pembeli.getId().equals(id_Pembeli)){
                indexPembeli = listPembeli.indexOf(pembeli);
            }
        }
        PembeliDropDown.setSelectedIndex(indexPembeli);
        
        
        setEditDeleteBtn(true);
    }//GEN-LAST:event_tablePembelianMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        
         try{
            TablePembelian pembelian = pembelianControl.showDataPembelian(searchInput.getText());
            if(pembelian.getRowCount()==0){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null,"Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                tablePembelian.setModel(pembelian);
            }
            clearText();
        }catch(Exception e){
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void CekTensiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CekTensiPanelMouseClicked
        // TODO add your handling code here:
        CekTensiView ctv = new CekTensiView();
        this.dispose();
        ctv.setVisible(true);
    }//GEN-LAST:event_CekTensiPanelMouseClicked

    private void LogoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoPanelMouseClicked
        // TODO add your handling code here:
        LobbyView lv = new LobbyView();
        this.dispose();
        lv.setVisible(true);
    }//GEN-LAST:event_LogoPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembelianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembelianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembelianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembelianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembelianView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CekTensiPanel;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JComboBox<Obat> ObatDropDown;
    private javax.swing.JComboBox<Pembeli> PembeliDropDown;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel iconApotek;
    private javax.swing.JLabel iconCekTensi;
    private javax.swing.JLabel iconPembelian;
    private javax.swing.JPanel isiPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCatatan;
    private javax.swing.JLabel lblCekTensi;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblNamaApotek;
    private javax.swing.JLabel lblObat;
    private javax.swing.JLabel lblPembeli;
    private javax.swing.JLabel lblPembelian;
    private javax.swing.JLabel lblTangga;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTable tablePembelian;
    private javax.swing.JTable tablePembelian1;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtCatatan;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTanggalPembelian;
    // End of variables declaration//GEN-END:variables
}
